version: "3.9"

services:


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: statshelper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 85hvP5npPj2fi4
    ports:
      - "5432:5432"
    volumes:
      - ./database:/database/data
    networks:
      - stats-helper

networks:
  stats-helper:
    driver: bridge
