version: "3.9"

services:


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: statshelper
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 85hvP5npPj2fi4
    ports:
      - "5432:5432"
    volumes:
      - ./database:/database/data
    networks:
      - stats-helper
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 85hvP5npPj2fi4
    depends_on:
      - db
    ports:
      - "5050:80"
    networks:
      - stats-helper
  
networks:
  stats-helper:
    driver: bridge
